---
###############################################################################
#                                                                             #
#                            WEBSITE CONFIGURATION                            #
#                                                                             #
###############################################################################

# --- base website settings ---

title: "Vote Up!"
description: "Find the nearest voting booth near you in the United States."
url: "https://voteup-stg.fosstivist.org"
year: "2020"


# --- general settings ---

baseurl: ""  # the subpath of your site, e.g. /blog
github_repo: "https://github.com/fosstivists/vote-up"
favicon_path: "/static/favicon.ico"
logo_path: "/static/logo.jpg"


# --- biography site information ---

email: team@fosstivist.org
blog: https://fosstivist.org/blog/


# --- build settings ---

markdown: kramdown
permalink: pretty  # no .html extensions
plugins:
  - jekyll-feed
  - jekyll-sitemap
theme: minima


# --- exclusions ---
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - CNAME
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - node_modules/
  - Rakefile
  - README.md
  - tmp
  - vendor
